name: Download latest Gradle build validation scripts
description: "Downloads the latest release of the build validation scripts for Gradle"

inputs:
  token:
    description: "GitHub token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download latest Gradle build validation scripts
      run: |
        # Set curl general options
        curlOpts=(--silent --fail --show-error --retry 3 --retry-delay 5 --location)

        # Set authorization header if needed
        if [ ! -z "${{ inputs.token }}" ]; then
          curlOpts+=(--header 'Authorization: Bearer ${{ inputs.token }}')
        fi

        # Get the download url of the latest release
        downloadUrl=$(curl "${curlOpts[@]}" https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest | jq -c '.assets[] | select(.content_type == "application/zip")' | jq -r .browser_download_url | grep -v maven)

        # Download the latest version of the build validation scripts
        curl "${curlOpts[@]}" --output gradle-enterprise-gradle-build-validation.zip $downloadUrl

        # Unzip the downloaded build validation scripts
        unzip -q -o gradle-enterprise-gradle-build-validation.zip
      shell: bash
